apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-odev
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: deployment
  template:
    metadata:
      labels:
        app: deployment
    spec:
      containers:
      - name: deployment-odev
        image: seyma1km/oxer-html
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: deployment-service
spec:
  type: NodePort
  selector:
    app: deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
