apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica-odevim
spec:
  replicas: 4
  selector:
    matchLabels:
      app: replica
  template:
    metadata:
      labels:
        app: replica
    spec:
      containers:
      - name: odevim-app
        image: seyma1km/oxer-html
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: replica-service
spec:
  type: NodePort
  selector:
    app: replica
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30006
